# Generated by Django 2.2 on 2019-04-09 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=15, verbose_name='Usuario')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('password', models.CharField(max_length=30, verbose_name='Contraseña')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('foto', models.ImageField(upload_to='usuario', verbose_name='Foto de Perfil')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre del Puesto')),
                ('Dias de Atención', models.CharField(max_length=30)),
                ('hora_apertura', models.TimeField(verbose_name='Hora de apertura')),
                ('hora_cierre', models.TimeField(verbose_name='Hora de Cierre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('puntuacion', models.IntegerField(verbose_name='Puntuación')),
                ('ubicacion', models.TextField(verbose_name='Coordenadas')),
                ('foto', models.ImageField(upload_to='puesto', verbose_name='Foto')),
                ('usuario', models.ManyToManyField(to='core.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('likes', models.IntegerField(verbose_name='Likes')),
                ('ubicacion', models.TextField(verbose_name='Coordenadas')),
                ('fecha_post', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Posteo')),
                ('foto', models.ImageField(upload_to='post', verbose_name='Captura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Usuario')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-fecha_post'],
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre del Plato')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('descripcion', models.TextField(verbose_name='Descripción del Plato')),
                ('foto', models.ImageField(upload_to='plato', verbose_name='Foto')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Puesto')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentario')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Puesto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Usuario')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentario',
                'ordering': ['-fecha'],
            },
        ),
    ]
